# Generated by Django 2.2.4 on 2019-08-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_processing_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importrequest',
            name='owner',
        ),
    ]
