# Generated by Django 2.2.4 on 2019-08-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_processing_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importrequest',
            name='ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='importrequest',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importrequest',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
