# Generated by Django 2.2.4 on 2019-08-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_processing_test', '0002_remove_importrequest_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrequest',
            name='ended',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='importrequest',
            name='started',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
